### ISSUE TITLE
Support launching single task

### ISSUE THREAD

**Issue by jeffnappi** [CircleCI-Public/aws-ecs-orb#10]
I would like to use this to be able to kick off a single ECS task. And then preferably retrieve the exit code and logs from the task.

**Comment by lokst** [comment]
Hi @jeffnappi , that's a great suggestion, I'll be looking into this.

**Comment by jeffnappi** [comment]
Awesome @lokst :)

An example scenario would be to run database migrations in an ECS task as part of a release.

**Comment by jeffnappi** [comment]
Any progress here @lokst? I might fork and tackle it myself - I have a need for this now.

**Comment by lokst** [comment]
@jeffnappi I haven't been able to make progress on this yet. We would welcome PR contributions if you have any! :)

**Comment by jrkienle** [comment]
Hey! This is definitely a feature I'd be interested in - has there been any progress on it so far?

**Comment by martinbjeldbak** [comment]
We'd be very interested in this feature too! Until then, I've hacked together the below job. Note that it assumes some environment variables are set within CircleCI.

It doesn't have any sense of whether the task completed successfully or not, similar to the `verify-revision-is-deployed` command

```yml
---
version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@0.0.8
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  run-release-tasks:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-region: AWS_REGION
      - aws-ecs/update-task-definition:
          family: ${AWS_TASK_DEFINITION}
      - run:
          name: Run release task
          command: |
            aws ecs run-task --cluster ${AWS_CLUSTER_NAME} --task-definition release --launch-type FARGATE --network-configuration awsvpcConfiguration="{subnets=[${PRIVATE_SUBNET_ONE}, ${PRIVATE_SUBNET_TWO}],securityGroups=[${AWS_FARGATE_SECURITY_GROUP}],assignPublicIp=DISABLED}"
```
