### ISSUE TITLE
No such file or directory: 'less': 'less'

### ISSUE THREAD

**Issue by bkovacev** [CircleCI-Public/aws-ecs-orb#103]
### Orb version
1.1.0

### What happened
The output of the CI task is not successful, but the job has ran just fine.

`config.yml`
```
  run-collectstatic:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - run:
          name: Setup ENV VAR
          command: |
            echo 'export ECS_SERVICE_NAME="${AWS_RESOURCE_NAME_PREFIX}-service"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/myrepo:${CIRCLE_SHA1}"' >> $BASH_ENV
      - run:
          name: Setup BRANCH
          command: |
            if [ $CIRCLE_BRANCH == "master" ]; then echo 'export CURRENT_BRANCH="production"' >> $BASH_ENV; else echo 'export CURRENT_BRANCH="${CIRCLE_BRANCH}"' >> $BASH_ENV; fi
      - run:
          name: Setup ECS
          command: |
            if [ $CIRCLE_BRANCH == "master" ]; then echo 'export ECS_CLUSTER_NAME="my-production-cluster"' >> $BASH_ENV; else echo 'export ECS_CLUSTER_NAME="my-${CIRCLE_BRANCH}-cluster"' >> $BASH_ENV; fi
      - aws-cli/install
      - aws-cli/setup
      - run:
          name: Get last task definition
          command: >
            STATIC_TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition myTask-${CURRENT_BRANCH} \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export STATIC_TASK_DEFINITION_ARN='${STATIC_TASK_DEFINITION_ARN}'" >> $BASH_ENV

      - aws-ecs/run-task:
          cluster: ${ECS_CLUSTER_NAME}
          task-definition: ${STATIC_TASK_DEFINITION_ARN}
          awsvpc: false
          launch-type: EC2
```

`CI output`
```
#!/bin/bash -eo pipefail
set -o noglob
if [ "EC2" == "FARGATE" ]; then
    echo "Setting --platform-version"
    set -- "$@" --platform-version "LATEST"
fi
if [ ! -z "" ]; then
    echo "Setting --started-by"
    set -- "$@" --started-by ""
fi
if [ ! -z "" ]; then
    echo "Setting --group"
    set -- "$@" --group ""
fi
if [ ! -z "" ]; then
    echo "Setting --overrides"
    set -- "$@" --overrides ""
fi
if [ ! -z "" ]; then
    echo "Setting --tags"
    set -- "$@" --tags ""
fi
if [ ! -z "" ]; then
    echo "Setting --placement-constraints"
    set -- "$@" --placement-constraints ""
fi
if [ ! -z "" ]; then
    echo "Setting --placement-strategy"
    set -- "$@" --placement-strategy ""
fi
if [ "false" == "true" ]; then
    echo "Setting --enable-ecs-managed-tags"
    set -- "$@" --enable-ecs-managed-tags
fi
if [ "false" == "true" ]; then
    echo "Setting --propagate-tags"
    set -- "$@" --propagate-tags "TASK_DEFINITION"
fi
if [ "false" == "true" ]; then
    echo "Setting --network-configuration"
    set -- "$@" --network-configuration awsvpcConfiguration="{subnets=[],securityGroups=[],assignPublicIp=DISABLED}"
fi

aws ecs run-task \
  --cluster ${ECS_CLUSTER_NAME} \
  --task-definition ${TASK_DEFINITION_ARN} \
  --count 1 \
  --launch-type EC2 \
  "$@"


[Errno 2] No such file or directory: 'less': 'less'

Exited with code exit status 255
```

### Expected behavior
The output of the CI task should be successful as the job has ran just fine on ECS.

**Comment by mhaley-miovision** [comment]
FWIW I am also hitting this calling lambda update-function:
```
aws  lambda update-function-code --function-name my-lambda-function --zip-file fileb://code.zip
```

**Comment by mhaley-miovision** [comment]
From https://github.com/aws/aws-cli/issues/5038 which links https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-output-pager.  I tried setting the `AWS_PAGER` envvar like it suggests and that seems to work.  My config is like so

```
jobs:
  build_and_publish_lambda:
    working_directory: ~/workdir
    executor: python/default
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_PAGER: ""
    steps:
      - checkout
      - aws-cli/setup
.........
```
