### ISSUE TITLE
Allow passing DockerHub credentials

### ISSUE THREAD

**Issue by blimmer** [CircleCI-Public/aws-ecs-orb#114]
## What would you like to be added

We'll need a way to pass the `auth` block to the `docker` configuration parameter ([docs](https://circleci.com/docs/2.0/configuration-reference/#docker)). I see that you can customize the docker image, but you can't pass `auth` credentials: https://github.com/CircleCI-Public/aws-ecs-orb/blob/0f7fce6f951ff6ccdcf76538efa781eef9efb5f0/src/orb.yml.hbs#L390-L391

## Why is this needed

Starting November 1, 2020, DockerHub will [begin rate-limiting image pulls from DockerHub](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). Users need a way to pass their DockerHub credentials to avoid the rate limit. Without providing this configuration option, deployments from CircleCI will be impacted.

## Workaround

I was able to work around this by recreating the `steps` from the job:

```yaml
deploy-service-update:
  # Use upstream image
  # https://github.com/CircleCI-Public/aws-ecs-orb/blob/0f7fce6f951ff6ccdcf76538efa781eef9efb5f0/src/orb.yml.hbs#L181-L185
  docker:
    - image: circleci/python:3.7.1
	  # !!! This is the important part that I can't do today
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_ACCESS_TOKEN
  steps:
    - aws-cli/install
    - aws-cli/setup
    - aws-ecs/update-service:
        cluster-name: "my-cluster"
        service-name: "my-service"
        family: "MyTaskDef"
        container-image-name-updates: "container=service,tag=my-service-${CIRCLE_SHA1}"
```

However, a parameter would be nice to use instead.
