### ISSUE TITLE
Cannot dynamically inject in env variables

### ISSUE THREAD

**Issue by stringbeans** [CircleCI-Public/aws-ecs-orb#13]
Hey there!

We want to inject environment variables into the **job** deploy-service-update or the **command** update-task-definition

the problem is that circleCI doesnt properly support passing environment variables between different steps of a job... and we currently fetch our environment variables from AWS param store.

it would be really cool if for **update-task-definition** you could do something like this:

```
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecs: circleci/aws-ecs@0.0.3

jobs:
  update-tag:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: "$AWS_ACCESS_KEY_ID"
          aws-region: "$AWS_REGION"
      - aws-ecs/update-service:
          family: "${MY_APP_PREFIX}-service"
          container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=stable"
          before: |
            export MY_APP_PREFIX=something_dynamic
workflows:
  deploy:
    jobs:
      - update-tag
```
