### ISSUE TITLE
Update run-task command to give access to the output from the aws cli

### ISSUE THREAD

**Issue by liron-quantum** [CircleCI-Public/aws-ecs-orb#135]
## Describe Request:
The run-task command in that job is great for starting the job, but it doesn't save the output of the run-task command anywhere, which means that there's no easy way to check on the status of the task and wait for it to run before going onto the next build step.

If this functionality could be added to the orb, it would be fantastic.

## Examples:
If the task IDs could be added into an environment variable, or if you could specify an output file that the orb command would pipe the output to.

For example, you could add:
```
run-output:
    description: |
          Specifies an output file on the local disk to save the output from the run-task CLI command.
    type: string
```

And then update the run_task script to be:
```
if [ -n "<<params.run-output>>" ]; then
  aws ecs run-task "$@" >> <<params.run-output>>
else
  aws ecs run-task "$@" 
fi
```
