### ISSUE TITLE
run-task overrides fails to evaluate env arguments

### ISSUE THREAD

**Issue by dsvensson** [CircleCI-Public/aws-ecs-orb#146]
## Orb version:

2.2.1

## What happened:

```
Error parsing parameter '--overrides': Expected: '=', received: '$' for input:
$OVERRIDES
^
```

## Expected behavior:

I expected that this would work:

```yaml
      - run:
          name: "foo"
          command: echo "export OVERRIDES=\"test\"" >> $BASH_ENV
      - aws-ecs/run-task:
          overrides: "${OVERRIDES}"
          ...
```
