### ISSUE TITLE
Add 'Deployment configuration' parameter for Blue/Green Deployment

### ISSUE THREAD

**Issue by geoL86** [CircleCI-Public/aws-ecs-orb#159]
## Describe Request:

Add additional optional parameter 'Deployment configuration' for 'update-service' and 'deploy-service-update' jobs.

## Examples:

```
xxx-xxx:
    executor: aws-cli/default
    resource_class: small
    steps:
      - aws-ecs/update-service:
          family: 'xxx'
          cluster-name: 'xxx'
          service-name: 'xxx'
          codedeploy-application-name: 'xxx'
          codedeploy-deployment-group-name: 'xxx'
          deployment-controller: 'CODE_DEPLOY'
        + deployment-configuration: 'xxx'
          codedeploy-load-balanced-container-name: 'nginx'
          codedeploy-load-balanced-container-port: 80
          container-image-name-updates: 'container=xxx,tag=xxx'
```

## Supporting Documentation Links:
https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html
