### ISSUE TITLE
Variable interpolation in overrides JSON

### ISSUE THREAD

**Issue by nford** [CircleCI-Public/aws-ecs-orb#160]
## Orb version:

2.2.1

## What happened:

```
...
environment:
      CLUSTER_NAME: foo-cluster
      CONTAINER_NAME: rails
    steps:
      - aws-cli/install
      - aws-authenticate
      - run:
          command: |
            aws sts get-caller-identity
- aws-ecs/run-task:
          cluster: '${CLUSTER_NAME}'
          overrides: '{"containerOverrides":[{"name": "${CONTAINER_NAME}", "environment": [{"name": "RUN_DB_MIGRATIONS","value": "true"}]}]}' 
...

An error occurred (InvalidParameterException) when calling the RunTask operation: name must match ^[a-zA-Z0-9\-_]+$
```
The same ENV VAR is used elsewhere without issue. If I replace ${CONTAINER_NAME} with the relevant string it works without issue. The Orb does not seem to interpolate the value within this JSON.

## Expected behavior:

name value should be populated
