### ISSUE TITLE
Single quotes in task definition are not supported

### ISSUE THREAD

**Issue by lokst** [CircleCI-Public/aws-ecs-orb#18]
Refer to https://github.com/CircleCI-Public/aws-ecs-orb/issues/16 for an example of the error that will result when using the `update-task-definition` command when the existing task definition contains a single quote.

**Comment by chrisbloemker** [comment]
Is there a fix for this? I'm having trouble, maybe it's on my end.

The command in my `config.yml`

```
- aws-ecs/update-service:
          family: <<parameters.ecs-task>>
          cluster-name: <<parameters.ecs-cluster>>
          service-name: <<parameters.ecs-service>>
          container-image-name-updates: "container=<<parameters.ecs-task>>,tag=${CIRCLE_BRANCH}-${CIRCLE_SHA1}"
          verify-revision-is-deployed: true
```

Resulting in the following error:
```

REVISION=$(aws ecs register-task-definition \
    --family frontend \
    --container-definitions "${CCI_ORB_AWS_ECS_CONTAINER_DEFS}" \
    "$@" \
    --output text \
    --query 'taskDefinition.taskDefinitionArn')
echo "Registered task definition: ${REVISION}"
echo "export CCI_ORB_AWS_ECS_REGISTERED_TASK_DFN='${REVISION}'" >> $BASH_ENV
/tmp/.bash_env-5d2d32607067050008132abe-0-build: line 4: unexpected EOF while looking for matching `"'
/tmp/.bash_env-5d2d32607067050008132abe-0-build: line 10: syntax error: unexpected end of file

Error parsing parameter '--container-definitions': Expected: '=', received: 'EOF' for input:

^
Exited with code 255
```

My guess is it's failing on that last export to `$BASH_ENV` ?
