### ISSUE TITLE
Not passing region flag in `aws ecs describe-task-definition` command

### ISSUE THREAD

**Issue by thedanielforum** [CircleCI-Public/aws-ecs-orb#21]
Hi,
I am having an issue where it can't find the task definition because the `--region` is missing in the `PREVIOUS_TASK_DEFINITION` command.
I have already set the `aws-region` option and the `AWS_DEFAULT_REGION` env variable options but with no luck.

Would appreciate some help with this one.

```
#!/bin/bash -eo pipefail
PREVIOUS_TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition redacted-api)
CONTAINER_IMAGE_NAME_UPDATES="$(echo container=redacted-api,tag=${CIRCLE_SHA1}")"
CONTAINER_ENV_VAR_UPDATES="$(echo )"
```

**Comment by lokst** [comment]
Hi, could you also try configuring the AWS_REGION project environment variable as the orb uses that by default? If that doesn't work could you open a support ticket at https://support.circleci.com/hc/en-us/requests/new and include a link to your build so that we can take a closer look?

**Comment by ozooxo** [comment]
This is because `aws-cli/install` and `aws-cli/configure` are not part of the command. You need to include them yourself. As shown in the example:

```
jobs:
  update-tag:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-region: $AWS_REGION
      - aws-ecs/update-service:
          family: '${MY_APP_PREFIX}-service'
          cluster-name: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=stable'
```

Notice that this is NOT consistent with https://circleci.com/orbs/registry/orb/circleci/aws-s3 and https://circleci.com/orbs/registry/orb/circleci/aws-ecr for which they are part of the command.
