### ISSUE TITLE
Allow passing ENV Vars to codedeploy_load_balanced_container_port

### ISSUE THREAD

**Issue by bassrock** [CircleCI-Public/aws-ecs-orb#211]
## Describe Request:

Right now since `codedeploy_load_balanced_container_port` requires the parameter to be an integer you can not pass through an ENV variable like `${ECS_CONTAINER_PORT}`. That will appear as a string and fail circleci validation even though the script itself would expand it when executed.

This is necessary in my configuration because I capture the container port from a terraform output and pass it through to the code deploy step in my CI.

## Examples:
```
      - aws-ecs/deploy_service_update:
          auth:
            - aws-cli/setup:
                profile: OIDC-USER
                role_arn: arn:aws:iam::123456789012:role/VALID_OIDC_ECS_ROLE
          cluster: ${MY_APP_PREFIX}-cluster
          container_image_name_updates: container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}
          codedeploy_load_balanced_container_port:${MY_PORT}
          family: ${MY_APP_PREFIX}-service
          profile: OIDC-USER
          requires:
            - aws-ecr/build-and-push-image
```
