### ISSUE TITLE
Cannot find a definition for command named aws-ecs/deploy-service-update

### ISSUE THREAD

**Issue by ascension** [CircleCI-Public/aws-ecs-orb#22]
I am getting this error when trying to use `aws-ecs/deploy-service-update`
`Cannot find a definition for command named aws-ecs/deploy-service-update`

Whats weird is that I can use `aws-ecs/update-service` but none of the jobs in the `aws-ecs` orb are available...

```
version: 2.1
orbs:
    utils:
        orbs:
            aws-ecr: circleci/aws-ecr@6.0.0
            aws-ecs: circleci/aws-ecs@0.0.8
        executors:
            ci:
                docker:
                    - image: $AWS_ECR_ACCOUNT_URL/ci:latest
            node:
                docker:
                    - image: circleci/node:10
        jobs:
            dependencies:
                description: Get deps and persist to workspace
                executor: node
                resource_class: large
                steps:
                    - checkout
                    - run:
                          name: Authenticate with registry
                          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
                    - run: yarn --frozen-lockfile
                    - persist_to_workspace:
                          root: .
                          paths:
                              - node_modules
                              - projects/*/node_modules
                              - packages/*/node_modules
                              - .npmrc
                    - run:
                          name: Ensure repo is clean from uncommitted changes, likely yarn.lock is out of date
                          command: git diff --quiet || exit 1
            release-packages:
                description: Build and release local dependency packages
                executor: node
                resource_class: large
                steps:
                    - checkout
                    - attach_workspace:
                          at: .
                    - run: ./node_modules/.bin/lerna publish from-package --yes

            build-image:
                description: Build docker image
                executor: ci
                resource_class: medium
                parameters:
                    project:
                        description: What project to build
                        type: string
                    project_dir:
                        description: Project's parent directory
                        type: string
                steps:
                    - checkout
                    - setup_remote_docker:
                          docker_layer_caching: true
                    - restore_cache:
                          keys:
                              - projects-cache-v1-{{ .Environment.CIRCLE_SHA1 }}
                    - run:
                          command: |
                              cp yarn.lock << parameters.project_dir >>/<< parameters.project >>
                    - aws-ecr/build-and-push-image:
                          extra-build-args: '--build-arg NPM_TOKEN=$NPM_TOKEN'
                          repo: '${AWS_RESOURCE_NAME_PREFIX}'
                          tag: '<< parameters.project >>-${CIRCLE_SHA1}'
                          dockerfile: '<< parameters.project_dir >>/<< parameters.project >>/Dockerfile'
                          path: '<< parameters.project_dir >>/<< parameters.project >>'
                          workspace-root: '<< parameters.project_dir >>/<< parameters.project >>'
            deploy-service:
                description: Build docker image
                executor: ci
                resource_class: medium
                parameters:
                    project:
                        description: What project to build
                        type: string
                    project_dir:
                        description: Project's parent directory
                        type: string
                steps:
                    - checkout
                    - setup_remote_docker:
                          docker_layer_caching: true
                    - restore_cache:
                          keys:
                              - projects-cache-v1-{{ .Environment.CIRCLE_SHA1 }}
                    - aws-ecs/deploy-service-update:
                          aws-region: ${AWS_DEFAULT_REGION}
                          family: '${AWS_RESOURCE_NAME_PREFIX}-service'
                          cluster-name: '${AWS_RESOURCE_NAME_PREFIX}-cluster'
                          container-image-name-updates: container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=<< parameters.project >>-${CIRCLE_SHA1}"

workflows:
    build-and-deploy:
        jobs:
            - utils/dependencies:
                  name: dependencies
                  context: GuiltySpark
            - utils/release-packages:
                  name: release-packages
                  filters:
                      branches:
                          only:
                              - master
                  requires:
                      - dependencies
            - utils/build-image:
                  name: build-web
                  context: GuiltySpark
                  project: web
                  project_dir: projects
                  requires:
                      - release-packages
            - utils/build-image:
                  name: build-graphql
                  context: GuiltySpark
                  project: graphql
                  project_dir: projects
                  requires:
                      - release-packages
            - utils/deploy-service:
                  name: deploy-graphql
                  context: GuiltySpark
                  project: web
                  project_dir: projects
                  requires:
                      - build-web

```
