### ISSUE TITLE
Register new task definition fails with "Error parsing parameter ..."

### ISSUE THREAD

**Issue by schaebo** [CircleCI-Public/aws-ecs-orb#86]
### Orb version

```
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@1.0.4
  aws-cli: circleci/aws-cli@0.1.18
version: 2.1
```

### What happened
With the following config.yml:
```
orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@1.0.4
  aws-cli: circleci/aws-cli@0.1.18
version: 2.1
jobs:
... //other jobs that build and push the containers to ECR


  deploy-to-staging:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Install dependencies
          command: |
            apk add py-pip
            pip install awscli
      - aws-ecs/update-service:
          family: "mytaskdef"
          service-name: "myservice"
          cluster-name: "mycluster"
          container-image-name-updates: "container=container1,image-and-tag=${ECR_URL}/container1:${CIRCLE_SHA1},container=container2,image-and-tag=${ECR_URL}/container2:${CIRCLE_SHA1},container=container3,image-and-tag=${ECR_URL}/container3:${CIRCLE_SHA1}"


workflows:
  version: 2
  build-test-deploy:
    jobs:
...
      - deploy-to-staging:
          context: env.staging
          requires:
            - build-and-push-container-1
            - build-and-push-container-2
            - build-and-push-container-3
...

```

I get the following error:
```
Error parsing parameter '--container-definitions': Expected: '=', received: 'EOF' for input:

^

Exited with code exit status 255
```
For debugging purposes I tried:
* start the container with SSH
* put the script from the UI job output of "Register new task definition" into an .sh file
* source the BASH_ENV file and run the script

Example:
<details>
  <summary>Click to expand</summary>

 script.sh
```
#!/bin/sh
if [ -n "${CCI_ORB_AWS_ECS_TASK_ROLE}" ]; then
    set -- "$@" --task-role-arn "${CCI_ORB_AWS_ECS_TASK_ROLE}"
fi
if [ -n "${CCI_ORB_AWS_ECS_EXECUTION_ROLE}" ]; then
    set -- "$@" --execution-role-arn "${CCI_ORB_AWS_ECS_EXECUTION_ROLE}"
fi
if [ -n "${CCI_ORB_AWS_ECS_NETWORK_MODE}" ]; then
    set -- "$@" --network-mode "${CCI_ORB_AWS_ECS_NETWORK_MODE}"
fi
if [ -n "${CCI_ORB_AWS_ECS_VOLUMES}" ] && [ "${CCI_ORB_AWS_ECS_VOLUMES}" != "[]" ]; then
    set -- "$@" --volumes "${CCI_ORB_AWS_ECS_VOLUMES}"
fi
if [ -n "${CCI_ORB_AWS_ECS_PLACEMENT_CONSTRAINTS}" ] && [ "${CCI_ORB_AWS_ECS_PLACEMENT_CONSTRAINTS}" != "[]" ]; then
    set -- "$@" --placement-constraints "${CCI_ORB_AWS_ECS_PLACEMENT_CONSTRAINTS}"
fi
if [ -n "${CCI_ORB_AWS_ECS_REQ_COMP}" ] && [ "${CCI_ORB_AWS_ECS_REQ_COMP}" != "[]" ]; then
    set -- "$@" --requires-compatibilities ${CCI_ORB_AWS_ECS_REQ_COMP}
fi
if [ -n "${CCI_ORB_AWS_ECS_TASK_CPU}" ]; then
    set -- "$@" --cpu "${CCI_ORB_AWS_ECS_TASK_CPU}"
fi
if [ -n "${CCI_ORB_AWS_ECS_TASK_MEMORY}" ]; then
    set -- "$@" --memory "${CCI_ORB_AWS_ECS_TASK_MEMORY}"
fi
if [ -n "${CCI_ORB_AWS_ECS_PID_MODE}" ]; then
    set -- "$@" --pid-mode "${CCI_ORB_AWS_ECS_PID_MODE}"
fi
if [ -n "${CCI_ORB_AWS_ECS_IPC_MODE}" ]; then
    set -- "$@" --ipc-mode "${CCI_ORB_AWS_ECS_IPC_MODE}"
fi
if [ -n "${CCI_ORB_AWS_ECS_TAGS}" ] && [ "${CCI_ORB_AWS_ECS_TAGS}" != "[]" ]; then
    set -- "$@" --tags "${CCI_ORB_AWS_ECS_TAGS}"
fi
if [ -n "${CCI_ORB_AWS_ECS_PROXY_CONFIGURATION}" ] && [ "${CCI_ORB_AWS_ECS_PROXY_CONFIGURATION}" != "{}" ]; then
    set -- "$@" --proxy-configuration "${CCI_ORB_AWS_ECS_PROXY_CONFIGURATION}"
fi
REVISION=$(aws ecs register-task-definition \
    --family mytaskdef \
    --container-definitions "${CCI_ORB_AWS_ECS_CONTAINER_DEFS}" \
    "$@" \
    --output text \
    --query 'taskDefinition.taskDefinitionArn')
echo "Registered task definition: ${REVISION}"
```

command:
```
94cxxxxb8:~# echo $BASH_ENV
/tmp/.bash_env-5dfxxxxxxxxxxx6ed-0-build
94cxxxxb8:~# . /tmp/.bash_env-5dfxxxxxxxxxxx6ed-0-build && ./script.sh
```

</details>

Then it works and updates the task definition with the correct values. This would suggest that the used parameters for the ORB are correct.

### Expected behavior

The ECS task definition and the service are updated.

Any help would be greatly appreciated.
