### ISSUE TITLE
Polling multiple service at once with `verify-revision-is-deployed`

### ISSUE THREAD

**Issue by ypresto** [CircleCI-Public/aws-ecs-orb#96]
## What would you like to be added

```
- verify-revision-is-deployed:
    services:
      - cluster-name: ...
        service-name: ...
        family-name: ...
        task-definition-arn: ...
      - cluster-name: ...
        service-name: ...
        family-name: ...
        task-definition-arn: ...
      - cluster-name: ...
        service-name: ...
        family-name: ...
        task-definition-arn: ...
```

## Why is this needed

We deploy, verify, then notify for multiple services with a single job of CircleCI. Currently, we have sequential `aws-ecs/update-service`, then sequential `verify-revision-is-deployed`, then `slack/status` steps.

So timeout of a `verify-revision-is-deployed` step depends on previous `verify-revision-is-deployed` step.

It can be configured as parallel verify jobs in the workflow but doing so is just wasting computation resources (because it is just "waiting").
